# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/stamp/Documents/NUS/Y2S1/EE2026/Project/MODS/MODS.srcs/sources_1/ip/homescreen_background/homescreen_background.xci
# IP: The module: 'homescreen_background' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/stamp/Documents/NUS/Y2S1/EE2026/Project/MODS/MODS.srcs/sources_1/ip/homescreen_background/homescreen_background_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'homescreen_background'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/stamp/Documents/NUS/Y2S1/EE2026/Project/MODS/MODS.srcs/sources_1/ip/homescreen_background/homescreen_background.xci
# IP: The module: 'homescreen_background' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/stamp/Documents/NUS/Y2S1/EE2026/Project/MODS/MODS.srcs/sources_1/ip/homescreen_background/homescreen_background_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'homescreen_background'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
