# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Tay Xu Yang/Documents/GitHub/EE2026_2425_Wed_AM_Team_13_Project/MODS/MODS.srcs/sources_1/ip/battleground_background/battleground_background.xci
# IP: The module: 'battleground_background' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tay Xu Yang/Documents/GitHub/EE2026_2425_Wed_AM_Team_13_Project/MODS/MODS.srcs/sources_1/ip/battleground_background/battleground_background_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'battleground_background'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Tay Xu Yang/Documents/GitHub/EE2026_2425_Wed_AM_Team_13_Project/MODS/MODS.srcs/sources_1/ip/battleground_background/battleground_background.xci
# IP: The module: 'battleground_background' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tay Xu Yang/Documents/GitHub/EE2026_2425_Wed_AM_Team_13_Project/MODS/MODS.srcs/sources_1/ip/battleground_background/battleground_background_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'battleground_background'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
